#!/usr/bin/env python3
"""Load the official DOGFOOD fixtures.json into seed_fixtures.sql.

Usage: python3 db/load_fixtures.py [fixtures.json] [db/seed_fixtures.sql]

Deterministic: fixture string ids map to stable UUIDs via sha256, so every
rebuild produces identical rows. Idempotent: every statement is guarded by
ON CONFLICT DO NOTHING (or guarded UPDATEs), so re-running never duplicates.

Fixture edge cases are preserved, not sanitized: the flat reviewer, the
incomplete batches, and the duplicate prj_07/prj_41 submission all load.
"""
import hashlib
import json
import sys


def fid(*parts: str) -> str:
    h = hashlib.sha256("|".join(parts).encode()).hexdigest()
    return f"{h[:8]}-{h[8:12]}-{h[12:16]}-{h[16:20]}-{h[20:32]}"


def lit(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    return "'" + str(value).replace("'", "''") + "'"


OPENJUDGE_HASH = (
    "scrypt$16384$8$1$9ed5eabbb71486e3373248d57d2a2cd1"
    "$dc1ce9cd8912414ec8d4236439c4fdd04463dc22e2cbab741464597c87a9028429ac46705efc6e888c06b72cdeefd6edb8fbd9aae5ec13ae4fe470366f16ae4a"
)

# Fixed acceptance sessions (named in .dogfood.toml [auth]).
SESSIONS = [
    ("organizer@example.org", "df-org-7f2a9c"),
    ("tomas.varga@example.org", "df-jdga-91bc4e"),
    ("wei.lindqvist@example.org", "df-jdgb-44de8a"),
    ("participant@example.org", "df-prt-2e88f1"),
]


def main() -> None:
    src = sys.argv[1] if len(sys.argv) > 1 else "fixtures.json"
    out = sys.argv[2] if len(sys.argv) > 2 else "db/seed_fixtures.sql"
    with open(src, encoding="utf-8") as f:
        fx = json.load(f)

    sql: list[str] = []
    sql.append("-- DOGFOOD fixtures (generated by db/load_fixtures.py — do not hand-edit).")
    sql.append("-- Source: https://dogfoodhack.com/spec/fixtures.json")

    ev = fx["event"]
    event_id = fid("event", ev["id"])
    sql.append(
        "insert into public.events (id, slug, name, tagline, description, starts_at, ends_at,"
        " submissions_open, judging_open, reviews_per_submission) values "
        f"({lit(event_id)}, 'sample-hack-2026', {lit(ev['name'])},"
        " 'Official DOGFOOD 2026 fixture event.', 'Loaded verbatim from fixtures.json."
        " Submissions closed (submissions_close is in the past).', NULL,"
        f" {lit(ev['submissions_close'])}, false, true, 3) on conflict (id) do nothing;"
    )

    track_ids = {}
    for t in fx["tracks"]:
        tid = fid("track", t["id"])
        track_ids[t["id"]] = tid
        slug = "".join(c if c.isalnum() else "-" for c in t["name"].lower()).strip("-") or "track"
        sql.append(
            f"insert into public.tracks (id, event_id, slug, name) values ({lit(tid)},"
            f" {lit(event_id)}, {lit(slug)}, {lit(t['name'])}) on conflict (id) do nothing;"
        )

    criteria_names: list[str] = []
    for s in fx["scores"]:
        for name in s["criteria"]:
            if name not in criteria_names:
                criteria_names.append(name)
    criteria_names.sort()
    crit_ids = {}
    for i, name in enumerate(criteria_names):
        cid = fid("criterion", ev["id"], name)
        crit_ids[name] = cid
        sql.append(
            "insert into public.criteria (id, event_id, name, description, weight, min_score,"
            f" max_score, position) values ({lit(cid)}, {lit(event_id)}, {lit(name)},"
            f" 'Fixture criterion.', 1, 1, 5, {i + 1}) on conflict (id) do nothing;"
        )

    team_names = {}
    for tm in fx["teams"]:
        team_id = fid("team", tm["id"])
        team_names[tm["id"]] = (team_id, tm["name"])
        sql.append(
            f"insert into public.teams (id, event_id, name, created_by) values ({lit(team_id)},"
            f" {lit(event_id)}, {lit(tm['name'])}, 'fixtures') on conflict (id) do nothing;"
        )
        for n, member in enumerate(tm["members"]):
            role = "owner" if n == 0 else "member"
            sql.append(
                "insert into public.team_members (team_id, user_key, role) values"
                f" ({lit(team_id)}, {lit(member)}, '{role}') on conflict do nothing;"
            )

    judge_ids = {}
    for j in fx["judges"]:
        jid = fid("judge", j["id"])
        judge_ids[j["id"]] = jid
        sql.append(
            "insert into public.judges (id, event_id, display_name, email, active) values"
            f" ({lit(jid)}, {lit(event_id)}, {lit(j['name'])}, {lit(j['email'])}, true)"
            " on conflict (id) do nothing;"
        )
        if j.get("tracks"):
            first = track_ids[j["tracks"][0]]
            sql.append(
                "insert into public.judge_scopes (judge_id, track_id, updated_at) values"
                f" ({lit(jid)}, {lit(first)}, now()) on conflict (judge_id) do nothing;"
            )

    # Acceptance + demo logins for two fixture judges (judge_a/b in .dogfood.toml).
    for email in ("tomas.varga@example.org", "wei.lindqvist@example.org"):
        handle = email.split("@")[0].replace(".", " ")
        sql.append(
            "insert into public.users (id, email, password_hash, display_name) values"
            f" ({lit(fid('user', email))}, {lit(email)}, {lit(OPENJUDGE_HASH)}, {lit(handle)})"
            " on conflict (email) do nothing;"
        )
        sql.append(
            "insert into public.user_roles (user_id, role) values"
            f" ({lit(fid('user', email))}, 'participant'), ({lit(fid('user', email))}, 'judge')"
            " on conflict do nothing;"
        )
    sql.append(
        "update public.judges set user_id = "
        f"{lit(fid('user', 'tomas.varga@example.org'))} where id = {lit(judge_ids['jdg_01'])}"
        " and user_id is null;"
    )
    sql.append(
        "update public.judges set user_id = "
        f"{lit(fid('user', 'wei.lindqvist@example.org'))} where id = {lit(judge_ids['jdg_02'])}"
        " and user_id is null;"
    )

    sub_ids = {}
    for p in fx["projects"]:
        pid = fid("project", p["id"])
        sub_ids[p["id"]] = pid
        team_id, team_name = team_names[p["team"]]
        sql.append(
            "insert into public.submissions (id, event_id, track_id, team_name, title, tagline,"
            " description, repo_url, tags, status, created_at, updated_at) values"
            f" ({lit(pid)}, {lit(event_id)}, {lit(track_ids[p['track']])}, {lit(team_name)},"
            f" {lit(p['title'])}, {lit(p['summary'])}, {lit(p['summary'])}, {lit(p['repo_url'])},"
            " '{}', 'submitted',"
            f" {lit(p['submitted_at'])}, {lit(p['submitted_at'])}) on conflict (id) do nothing;"
        )

    for s in fx["scores"]:
        jid = judge_ids[s["judge"]]
        pid = sub_ids[s["project"]]
        aid = fid("assign", s["judge"], s["project"])
        comment = s.get("comment") or ""
        sql.append(
            "insert into public.assignments (id, event_id, judge_id, submission_id, status,"
            f" submitted_at, comment) values ({lit(aid)}, {lit(event_id)}, {lit(jid)}, {lit(pid)},"
            f" 'submitted', (select created_at from public.submissions where id = {lit(pid)}),"
            f" {lit(comment) if comment else 'NULL'}) on conflict (id) do nothing;"
        )
        for name, value in s["criteria"].items():
            sql.append(
                "insert into public.scores (assignment_id, criterion_id, value) values"
                f" ({lit(aid)}, {lit(crit_ids[name])}, {int(value)})"
                " on conflict (assignment_id, criterion_id) do nothing;"
            )

    # Deterministic acceptance sessions (tokens named in .dogfood.toml).
    sessions = [
        ("organizer@example.org", "df-org-7f2a9c"),
        ("tomas.varga@example.org", "df-jdga-91bc4e"),
        ("wei.lindqvist@example.org", "df-jdgb-44de8a"),
        ("participant@example.org", "df-prt-2e88f1"),
    ]
    for email, token in sessions:
        digest = hashlib.sha256(token.encode()).hexdigest()
        if email in ("organizer@example.org", "participant@example.org"):
            uid = {
                "organizer@example.org": "99999999-0000-0000-0000-000000000001",
                "participant@example.org": "99999999-0000-0000-0000-000000000003",
            }[email]
            sql.append(
                "insert into public.sessions (user_id, token_hash, expires_at) values"
                f" ({lit(uid)}, '{digest}', '2030-01-01T00:00:00Z')"
                " on conflict (token_hash) do nothing;"
            )
        else:
            sql.append(
                "insert into public.sessions (user_id, token_hash, expires_at)"
                f" select {lit(fid('user', email))}, '{digest}', '2030-01-01T00:00:00Z'"
                " where exists (select 1 from public.users where id"
                f" = {lit(fid('user', email))}) on conflict (token_hash) do nothing;"
            )

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(sql) + "\n")
    print(f"wrote {out}: {len(sql)} statements")


if __name__ == "__main__":
    main()
