/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedJudgeRouteImport } from './routes/_authenticated/judge'
import { Route as AuthenticatedObservatoryRouteImport } from './routes/_authenticated/observatory'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as OrganismsSubmissionIdRouteImport } from './routes/organisms.$submissionId'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as AuthenticatedReceiptProjectIdRouteImport } from './routes/_authenticated/receipt.$projectId'
import { Route as AuthenticatedTeamTokenRouteImport } from './routes/_authenticated/team.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJudgeRoute = AuthenticatedJudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObservatoryRoute =
  AuthenticatedObservatoryRouteImport.update({
    id: '/observatory',
    path: '/observatory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrganismsSubmissionIdRoute = OrganismsSubmissionIdRouteImport.update({
  id: '/organisms/$submissionId',
  path: '/organisms/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const AuthenticatedReceiptProjectIdRoute =
  AuthenticatedReceiptProjectIdRouteImport.update({
    id: '/receipt/$projectId',
    path: '/receipt/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamTokenRoute = AuthenticatedTeamTokenRouteImport.update({
  id: '/team/$token',
  path: '/team/$token',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/judge': typeof AuthenticatedJudgeRoute
  '/observatory': typeof AuthenticatedObservatoryRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/organisms/$submissionId': typeof OrganismsSubmissionIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/receipt/$projectId': typeof AuthenticatedReceiptProjectIdRoute
  '/team/$token': typeof AuthenticatedTeamTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/judge': typeof AuthenticatedJudgeRoute
  '/observatory': typeof AuthenticatedObservatoryRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/organisms/$submissionId': typeof OrganismsSubmissionIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/receipt/$projectId': typeof AuthenticatedReceiptProjectIdRoute
  '/team/$token': typeof AuthenticatedTeamTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/judge': typeof AuthenticatedJudgeRoute
  '/_authenticated/observatory': typeof AuthenticatedObservatoryRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/organisms/$submissionId': typeof OrganismsSubmissionIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/_authenticated/receipt/$projectId': typeof AuthenticatedReceiptProjectIdRoute
  '/_authenticated/team/$token': typeof AuthenticatedTeamTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/projects'
    | '/admin'
    | '/judge'
    | '/observatory'
    | '/submit'
    | '/organisms/$submissionId'
    | '/projects/$id'
    | '/receipt/$projectId'
    | '/team/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/projects'
    | '/admin'
    | '/judge'
    | '/observatory'
    | '/submit'
    | '/organisms/$submissionId'
    | '/projects/$id'
    | '/receipt/$projectId'
    | '/team/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/projects'
    | '/_authenticated/admin'
    | '/_authenticated/judge'
    | '/_authenticated/observatory'
    | '/_authenticated/submit'
    | '/organisms/$submissionId'
    | '/projects/$id'
    | '/_authenticated/receipt/$projectId'
    | '/_authenticated/team/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  OrganismsSubmissionIdRoute: typeof OrganismsSubmissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/judge': {
      id: '/_authenticated/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof AuthenticatedJudgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/observatory': {
      id: '/_authenticated/observatory'
      path: '/observatory'
      fullPath: '/observatory'
      preLoaderRoute: typeof AuthenticatedObservatoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/organisms/$submissionId': {
      id: '/organisms/$submissionId'
      path: '/organisms/$submissionId'
      fullPath: '/organisms/$submissionId'
      preLoaderRoute: typeof OrganismsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/_authenticated/receipt/$projectId': {
      id: '/_authenticated/receipt/$projectId'
      path: '/receipt/$projectId'
      fullPath: '/receipt/$projectId'
      preLoaderRoute: typeof AuthenticatedReceiptProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/$token': {
      id: '/_authenticated/team/$token'
      path: '/team/$token'
      fullPath: '/team/$token'
      preLoaderRoute: typeof AuthenticatedTeamTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedJudgeRoute: typeof AuthenticatedJudgeRoute
  AuthenticatedObservatoryRoute: typeof AuthenticatedObservatoryRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
  AuthenticatedReceiptProjectIdRoute: typeof AuthenticatedReceiptProjectIdRoute
  AuthenticatedTeamTokenRoute: typeof AuthenticatedTeamTokenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedJudgeRoute: AuthenticatedJudgeRoute,
  AuthenticatedObservatoryRoute: AuthenticatedObservatoryRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
  AuthenticatedReceiptProjectIdRoute: AuthenticatedReceiptProjectIdRoute,
  AuthenticatedTeamTokenRoute: AuthenticatedTeamTokenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  OrganismsSubmissionIdRoute: OrganismsSubmissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
