revoke execute on function public.has_role(uuid, public.app_role) from public;
revoke execute on function public.owns_judge(uuid) from public;
revoke execute on function public.owns_assignment(uuid) from public;
revoke execute on function public.assigned_to_me(uuid) from public;
revoke execute on function public.handle_new_user() from public;
revoke execute on function public.touch_updated_at() from public;
grant execute on function public.has_role(uuid, public.app_role) to authenticated, service_role;
grant execute on function public.owns_judge(uuid) to authenticated, service_role;
grant execute on function public.owns_assignment(uuid) to authenticated, service_role;
grant execute on function public.assigned_to_me(uuid) to authenticated, service_role;
grant execute on function public.handle_new_user() to service_role;
grant execute on function public.touch_updated_at() to service_role;
